### ISSUE TITLE
ReferenceError: ACC is not defined

### ISSUE THREAD

**Issue by meiti** [obarabanov/gps-server.js#1]
I have a Teltonika FM1120 device. How can I fix the following error:

ERROR [/home/meiti/gps/gps-server.js/modules/parsing/parser.js] parsing failure: ReferenceError: ACC is not defined
ERROR [/home/meiti/gps/gps-server.js/gps-server.js] Data wasn't parsed. Connection dropped.

**Comment by meiti** [comment]
I fixed the error by adding the following lines in the teltonika.js file:

var ACC = 1;
var DOOR = 2;
var Analog = 4;
var GSM = 5;
var SPEED = 6;
var VOLTAGE = 7;
var GPSPOWER = 8;
var TEMPERATURE = 9;
var ODOMETER = 16;
var STOP = 20;
var TRIP = 28;
var IMMOBILIZER = 29;
var AUTHORIZED = 30;
var GREEDRIVING = 31;
var OVERSPEED = 33;

**Comment by obarabanov** [comment]
ok cool you were able to fix that error by yourself.
Let me know if you have any more questions.
