### ISSUE TITLE
Teltonika FM1120 (Module) resends sent data

### ISSUE THREAD

**Issue by meiti** [obarabanov/gps-server.js#2]
Teltonika resends sent data repeatedly with no change in records.

Based on FMXXXX Protocols documentation: 
After server receives packet and parses it, server must report to module number of data received as integer (four bytes). If sent data number and reported by server doesn’t match module resends sent data.

How can I solve this problem?

**Comment by obarabanov** [comment]
Hi,
can you share that "FMXXXX Protocols documentation" with me, so I could figure out how this issue can be solved ? You're welcome to attach it right here.
Thanks!

**Comment by meiti** [comment]
Hi

Thanks I solved the issue by adding the following code to teltonika.js:
function parseDataPacket(socket, data) {
           ....
(Line Number: 155)  
            var mb = new Buffer(4);
            mb.fill(0);
            mb[3] = buf[i-1];
            socket.write(mb);
